/*
 * Copyright [2022-2023] [Xebisco]
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.xebisco.yield.physics;

import org.jbox2d.callbacks.ContactImpulse;
import org.jbox2d.collision.Manifold;
import org.jbox2d.dynamics.contacts.Contact;

public interface ContactListener extends BasicContactListener {
    /**
     * The preSolve function is a method used to handle contact and manifold information before
     * a collision occurs.
     *
     * @param var1 The first parameter, var1, is of type Contact and represents the contact point between two colliding
     * objects. It contains information about the collision such as the two objects involved, the point of contact, and the
     * normal vector of the collision.
     * @param var2 The var2 parameter in the preSolve method is a Manifold object that represents the contact manifold
     * between two colliding bodies. The manifold contains information about the contact points, normal vector, and other
     * properties of the collision.
     */
    void preSolve(Contact var1, Manifold var2);

    /**
     * The postSolve function is a method used to handle contact information after
     * a collision occurs.
     *
     * @param var1 The first parameter, var1, is a Contact object that represents the collision between two physics bodies.
     * It contains information such as the two bodies involved in the collision, the point of contact, and the normal
     * vector of the collision.
     * @param var2 The var2 parameter in the postSolve method is an object of the ContactImpulse class. It contains
     * information about the impulses generated by the collision between two bodies in the physics simulation. This
     * information can be used to calculate the amount of force applied during the collision and to determine the resulting
     * motion of
     */
    void postSolve(Contact var1, ContactImpulse var2);
}
